// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spa_Management_System.Data;

#nullable disable

namespace Spa_Management_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251130235642_AddSyncTrackingColumns")]
    partial class AddSyncTrackingColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Spa_Management_System.Models.Appointment", b =>
                {
                    b.Property<long>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("appointment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AppointmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_at");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("ScheduledEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_end");

                    b.Property<DateTime>("ScheduledStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sync_id");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sync_status");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int")
                        .HasColumnName("sync_version");

                    b.HasKey("AppointmentId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("Spa_Management_System.Models.AppointmentService", b =>
                {
                    b.Property<long>("ApptSrvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("appt_srv_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ApptSrvId"));

                    b.Property<long>("AppointmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("appointment_id");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("commission_amount");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<long?>("TherapistEmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("therapist_employee_id");

                    b.HasKey("ApptSrvId");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TherapistEmployeeId");

                    b.ToTable("AppointmentService");
                });

            modelBuilder.Entity("Spa_Management_System.Models.AuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditId"));

                    b.Property<string>("Action")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("action");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("change_summary");

                    b.Property<long?>("ChangedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("changed_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("entity_name");

                    b.HasKey("AuditId");

                    b.HasIndex("ChangedByUserId");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("Spa_Management_System.Models.CrmNote", b =>
                {
                    b.Property<long>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("note_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NoteId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.HasKey("NoteId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CRM_Note");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("customer_code");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnName("is_archived");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_at");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_synced_at");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int")
                        .HasColumnName("loyalty_points");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sync_id");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sync_status");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int")
                        .HasColumnName("sync_version");

                    b.HasKey("CustomerId");

                    b.HasIndex("CustomerCode")
                        .IsUnique()
                        .HasFilter("[customer_code] IS NOT NULL");

                    b.HasIndex("PersonId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Employee", b =>
                {
                    b.Property<long>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmployeeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("hire_date");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_at");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sync_id");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sync_status");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int")
                        .HasColumnName("sync_version");

                    b.HasKey("EmployeeId");

                    b.HasIndex("PersonId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Spa_Management_System.Models.EmployeeAttendance", b =>
                {
                    b.Property<long>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("attendance_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AttendanceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("days_worked");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("work_date");

                    b.HasKey("AttendanceId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EmployeeId", "WorkDate")
                        .IsUnique();

                    b.ToTable("EmployeeAttendance");
                });

            modelBuilder.Entity("Spa_Management_System.Models.EmployeeServiceCommission", b =>
                {
                    b.Property<long>("CommissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("commission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CommissionId"));

                    b.Property<string>("CommissionType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("commission_type");

                    b.Property<decimal>("CommissionValue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("commission_value");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2")
                        .HasColumnName("effective_from");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2")
                        .HasColumnName("effective_to");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnName("is_archived");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.HasKey("CommissionId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceId");

                    b.ToTable("EmployeeServiceCommission");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Expense", b =>
                {
                    b.Property<long>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("expense_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ExpenseId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("description");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expense_date");

                    b.Property<long?>("JournalId")
                        .HasColumnType("bigint")
                        .HasColumnName("journal_id");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_at");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_synced_at");

                    b.Property<long?>("LedgerAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("ledger_account_id");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reference_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sync_id");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sync_status");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int")
                        .HasColumnName("sync_version");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vendor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("vendor");

                    b.HasKey("ExpenseId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("JournalId");

                    b.HasIndex("LedgerAccountId");

                    b.ToTable("Expense");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Inventory", b =>
                {
                    b.Property<long>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InventoryId"));

                    b.Property<DateTime?>("LastCountedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_counted_at");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_at");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_synced_at");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<decimal>("QuantityOnHand")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("quantity_on_hand");

                    b.Property<decimal>("ReorderLevel")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("reorder_level");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sync_id");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sync_status");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int")
                        .HasColumnName("sync_version");

                    b.HasKey("InventoryId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("Spa_Management_System.Models.JournalEntry", b =>
                {
                    b.Property<long>("JournalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("journal_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("JournalId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("JournalNo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("journal_no");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_at");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_synced_at");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sync_id");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sync_status");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int")
                        .HasColumnName("sync_version");

                    b.HasKey("JournalId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("JournalNo")
                        .IsUnique()
                        .HasFilter("[journal_no] IS NOT NULL");

                    b.ToTable("JournalEntry");
                });

            modelBuilder.Entity("Spa_Management_System.Models.JournalEntryLine", b =>
                {
                    b.Property<long>("JournalLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("journal_line_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("JournalLineId"));

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("credit");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("debit");

                    b.Property<long>("JournalId")
                        .HasColumnType("bigint")
                        .HasColumnName("journal_id");

                    b.Property<long>("LedgerAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("ledger_account_id");

                    b.Property<string>("LineMemo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("line_memo");

                    b.HasKey("JournalLineId");

                    b.HasIndex("JournalId");

                    b.HasIndex("LedgerAccountId");

                    b.ToTable("JournalEntryLine");
                });

            modelBuilder.Entity("Spa_Management_System.Models.LedgerAccount", b =>
                {
                    b.Property<long>("LedgerAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ledger_account_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LedgerAccountId"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("account_type");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalBalance")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("normal_balance");

                    b.HasKey("LedgerAccountId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LedgerAccount");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Payment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_at");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_synced_at");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("payment_method");

                    b.Property<long?>("RecordedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<long>("SaleId")
                        .HasColumnType("bigint")
                        .HasColumnName("sale_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sync_id");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sync_status");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int")
                        .HasColumnName("sync_version");

                    b.HasKey("PaymentId");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("SaleId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Payroll", b =>
                {
                    b.Property<long>("PayrollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("payroll_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PayrollId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("daily_rate");

                    b.Property<int>("DaysWorked")
                        .HasColumnType("int")
                        .HasColumnName("days_worked");

                    b.Property<decimal>("Deductions")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("deductions");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<decimal>("GrossPay")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("gross_pay");

                    b.Property<long?>("JournalId")
                        .HasColumnType("bigint")
                        .HasColumnName("journal_id");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_at");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_synced_at");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("net_pay");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("period_end");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("period_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sync_id");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sync_status");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int")
                        .HasColumnName("sync_version");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PayrollId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("JournalId");

                    b.ToTable("Payroll");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Person", b =>
                {
                    b.Property<long>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PersonId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("first_name");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sync_id");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sync_status");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int")
                        .HasColumnName("sync_version");

                    b.HasKey("PersonId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("cost_price");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_at");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("sku");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sync_id");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sync_status");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int")
                        .HasColumnName("sync_version");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("ProductId");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasFilter("[sku] IS NOT NULL");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Spa_Management_System.Models.PurchaseOrder", b =>
                {
                    b.Property<long>("PoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("po_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PoId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("PoNumber")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("po_number");

                    b.Property<string>("Status")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("status");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.HasKey("PoId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PoNumber")
                        .IsUnique()
                        .HasFilter("[po_number] IS NOT NULL");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrder");
                });

            modelBuilder.Entity("Spa_Management_System.Models.PurchaseOrderItem", b =>
                {
                    b.Property<long>("PoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("po_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PoItemId"));

                    b.Property<long>("PoId")
                        .HasColumnType("bigint")
                        .HasColumnName("po_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<decimal>("QtyOrdered")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("qty_ordered");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("unit_cost");

                    b.HasKey("PoItemId");

                    b.HasIndex("PoId");

                    b.HasIndex("ProductId");

                    b.ToTable("PurchaseOrderItem");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Role", b =>
                {
                    b.Property<short>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("RoleId"));

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Sale", b =>
                {
                    b.Property<long>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sale_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SaleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_at");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("payment_status");

                    b.Property<string>("SaleNumber")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("sale_number");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sync_id");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sync_status");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int")
                        .HasColumnName("sync_version");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("SaleId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SaleNumber")
                        .IsUnique()
                        .HasFilter("[sale_number] IS NOT NULL");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("Spa_Management_System.Models.SaleItem", b =>
                {
                    b.Property<long>("SaleItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sale_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SaleItemId"));

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("item_type");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("line_total");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("qty");

                    b.Property<long>("SaleId")
                        .HasColumnType("bigint")
                        .HasColumnName("sale_id");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<long?>("TherapistEmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("therapist_employee_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("SaleItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TherapistEmployeeId");

                    b.ToTable("SaleItem");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Service", b =>
                {
                    b.Property<long>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ServiceId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified_at");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price");

                    b.Property<int?>("ServiceCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("service_category_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sync_id");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sync_status");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int")
                        .HasColumnName("sync_version");

                    b.HasKey("ServiceId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[code] IS NOT NULL");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("Spa_Management_System.Models.ServiceCategory", b =>
                {
                    b.Property<int>("ServiceCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("service_category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceCategoryId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("ServiceCategoryId");

                    b.ToTable("ServiceCategory");
                });

            modelBuilder.Entity("Spa_Management_System.Models.StockTransaction", b =>
                {
                    b.Property<long>("StockTxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("stock_tx_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StockTxId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("qty");

                    b.Property<string>("Reference")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("reference");

                    b.Property<string>("TxType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tx_type");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("unit_cost");

                    b.HasKey("StockTxId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("StockTransaction");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Supplier", b =>
                {
                    b.Property<long>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SupplierId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("contact_person");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone");

                    b.HasKey("SupplierId");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("Spa_Management_System.Models.UserAccount", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserAccount");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Appointment", b =>
                {
                    b.HasOne("Spa_Management_System.Models.UserAccount", "CreatedByUser")
                        .WithMany("Appointments")
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("Spa_Management_System.Models.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Spa_Management_System.Models.AppointmentService", b =>
                {
                    b.HasOne("Spa_Management_System.Models.Appointment", "Appointment")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spa_Management_System.Models.Service", "Service")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spa_Management_System.Models.Employee", "TherapistEmployee")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("TherapistEmployeeId");

                    b.Navigation("Appointment");

                    b.Navigation("Service");

                    b.Navigation("TherapistEmployee");
                });

            modelBuilder.Entity("Spa_Management_System.Models.AuditLog", b =>
                {
                    b.HasOne("Spa_Management_System.Models.UserAccount", "ChangedByUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ChangedByUserId");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("Spa_Management_System.Models.CrmNote", b =>
                {
                    b.HasOne("Spa_Management_System.Models.UserAccount", "CreatedByUser")
                        .WithMany("CrmNotes")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spa_Management_System.Models.Customer", "Customer")
                        .WithMany("CrmNotes")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Customer", b =>
                {
                    b.HasOne("Spa_Management_System.Models.Person", "Person")
                        .WithMany("Customers")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Employee", b =>
                {
                    b.HasOne("Spa_Management_System.Models.Person", "Person")
                        .WithMany("Employees")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spa_Management_System.Models.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Spa_Management_System.Models.EmployeeAttendance", b =>
                {
                    b.HasOne("Spa_Management_System.Models.UserAccount", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("Spa_Management_System.Models.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Spa_Management_System.Models.EmployeeServiceCommission", b =>
                {
                    b.HasOne("Spa_Management_System.Models.Employee", "Employee")
                        .WithMany("EmployeeServiceCommissions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spa_Management_System.Models.Service", "Service")
                        .WithMany("EmployeeServiceCommissions")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Expense", b =>
                {
                    b.HasOne("Spa_Management_System.Models.UserAccount", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("Spa_Management_System.Models.JournalEntry", "JournalEntry")
                        .WithMany()
                        .HasForeignKey("JournalId");

                    b.HasOne("Spa_Management_System.Models.LedgerAccount", "LedgerAccount")
                        .WithMany()
                        .HasForeignKey("LedgerAccountId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("JournalEntry");

                    b.Navigation("LedgerAccount");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Inventory", b =>
                {
                    b.HasOne("Spa_Management_System.Models.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("Spa_Management_System.Models.Inventory", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Spa_Management_System.Models.JournalEntry", b =>
                {
                    b.HasOne("Spa_Management_System.Models.UserAccount", "CreatedByUser")
                        .WithMany("JournalEntries")
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Spa_Management_System.Models.JournalEntryLine", b =>
                {
                    b.HasOne("Spa_Management_System.Models.JournalEntry", "JournalEntry")
                        .WithMany("JournalEntryLines")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spa_Management_System.Models.LedgerAccount", "LedgerAccount")
                        .WithMany("JournalEntryLines")
                        .HasForeignKey("LedgerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JournalEntry");

                    b.Navigation("LedgerAccount");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Payment", b =>
                {
                    b.HasOne("Spa_Management_System.Models.UserAccount", "RecordedByUser")
                        .WithMany("Payments")
                        .HasForeignKey("RecordedByUserId");

                    b.HasOne("Spa_Management_System.Models.Sale", "Sale")
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordedByUser");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Payroll", b =>
                {
                    b.HasOne("Spa_Management_System.Models.UserAccount", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("Spa_Management_System.Models.Employee", "Employee")
                        .WithMany("Payrolls")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spa_Management_System.Models.JournalEntry", "JournalEntry")
                        .WithMany()
                        .HasForeignKey("JournalId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Employee");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("Spa_Management_System.Models.PurchaseOrder", b =>
                {
                    b.HasOne("Spa_Management_System.Models.UserAccount", "CreatedByUser")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("Spa_Management_System.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Spa_Management_System.Models.PurchaseOrderItem", b =>
                {
                    b.HasOne("Spa_Management_System.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderItems")
                        .HasForeignKey("PoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spa_Management_System.Models.Product", "Product")
                        .WithMany("PurchaseOrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Sale", b =>
                {
                    b.HasOne("Spa_Management_System.Models.UserAccount", "CreatedByUser")
                        .WithMany("Sales")
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("Spa_Management_System.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Spa_Management_System.Models.SaleItem", b =>
                {
                    b.HasOne("Spa_Management_System.Models.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductId");

                    b.HasOne("Spa_Management_System.Models.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spa_Management_System.Models.Service", "Service")
                        .WithMany("SaleItems")
                        .HasForeignKey("ServiceId");

                    b.HasOne("Spa_Management_System.Models.Employee", "TherapistEmployee")
                        .WithMany("SaleItems")
                        .HasForeignKey("TherapistEmployeeId");

                    b.Navigation("Product");

                    b.Navigation("Sale");

                    b.Navigation("Service");

                    b.Navigation("TherapistEmployee");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Service", b =>
                {
                    b.HasOne("Spa_Management_System.Models.ServiceCategory", "ServiceCategory")
                        .WithMany("Services")
                        .HasForeignKey("ServiceCategoryId");

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("Spa_Management_System.Models.StockTransaction", b =>
                {
                    b.HasOne("Spa_Management_System.Models.UserAccount", "CreatedByUser")
                        .WithMany("StockTransactions")
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("Spa_Management_System.Models.Product", "Product")
                        .WithMany("StockTransactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Spa_Management_System.Models.UserAccount", b =>
                {
                    b.HasOne("Spa_Management_System.Models.Employee", "Employee")
                        .WithMany("UserAccounts")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentServices");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Customer", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("CrmNotes");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Employee", b =>
                {
                    b.Navigation("AppointmentServices");

                    b.Navigation("Attendances");

                    b.Navigation("EmployeeServiceCommissions");

                    b.Navigation("Payrolls");

                    b.Navigation("SaleItems");

                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("Spa_Management_System.Models.JournalEntry", b =>
                {
                    b.Navigation("JournalEntryLines");
                });

            modelBuilder.Entity("Spa_Management_System.Models.LedgerAccount", b =>
                {
                    b.Navigation("JournalEntryLines");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Person", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Product", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("PurchaseOrderItems");

                    b.Navigation("SaleItems");

                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("Spa_Management_System.Models.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderItems");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Role", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Sale", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Service", b =>
                {
                    b.Navigation("AppointmentServices");

                    b.Navigation("EmployeeServiceCommissions");

                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("Spa_Management_System.Models.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Spa_Management_System.Models.Supplier", b =>
                {
                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("Spa_Management_System.Models.UserAccount", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("AuditLogs");

                    b.Navigation("CrmNotes");

                    b.Navigation("JournalEntries");

                    b.Navigation("Payments");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("Sales");

                    b.Navigation("StockTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
